version: '3.4'

services:
    ###############
    consul:
        image: consul:${TAG:-latest}
        command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
        hostname: consul
        container_name: le-consul
        networks:
            - lang-exchange-network
        restart: always
        ports:
        - "8500:8500"
    ###############
    # le-api-gateway:
    #   image: thuongnguyen158/le-api-gateway:latest
    #   container_name: api-gateway
    #   environment:
    #     ASPNETCORE_ENVIRONMENT: Development

    #   depends_on:
    #     - le-file-service
    #     - consul
    #   networks:
    #     - lang-exchange-network
    #   restart: always
    #   ports:
    #   - "7777:80"
    ###############
    # access url to see http://localhost:5000/swagger/index.html
    le-file-service:
      image: thuongnguyen158/le-file-service:latest
      container_name: file-service
      environment:
        ASPNETCORE_ENVIRONMENT: Development
        S3_BUCKET_NAME: language-exchanged
        AWS_ACCESS_KEY_ID: empty
        AWS_SECRET_ACCESS_KEY: empty
        MINIO_HOST: http://127.0.0.1:9000
        CONSUL_URL: http://consul:8500

      depends_on:
        - consul
      networks:
        - lang-exchange-network
      restart: always
      ports:
      - "5000:80"
    ###############
    # access url to see http://localhost:5002/swagger/index.html
    le-user-service:
      image: thuongnguyen158/le-user-service:latest
      container_name: user-service
      environment:
        ASPNETCORE_ENVIRONMENT: Development
        CONSUL_URL: http://consul:8500
        DB_CONNECTION_STRING: ""

      depends_on:
        - consul
      networks:
        - lang-exchange-network
      restart: always
      ports:
      - "5002:80"

    ###############
    # access url to see http://localhost:8080
    le-webapp-service:
      image: thuongnguyen158/le-web-app:latest
      container_name: web-app
      environment:
        REACT_APP_API_URL_ROOT: ""
      networks:
        - lang-exchange-network
      restart: always
      ports:
      - "8080:80"
        
networks:
    lang-exchange-network:
        driver: bridge