version: '3.4'

services:
    ###############
    consul:
        image: consul:${TAG:-latest}
        command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
        hostname: consul
        container_name: le-consul
        networks:
            - lang-exchange-network
        restart: always
        ports:
        - "8500:8500"

    ###############
    zookeeper-server:
        image: bitnami/zookeeper:latest
        container_name: zookeeper
        ports:
        - "2181:80"
        environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
            - lang-exchange-network
        restart: always

    kafka:
        image: bitnami/kafka:latest
        container_name: kafka
        depends_on:
        - zookeeper-server
        ports:
        - "9093:9093"
        - "9092:9092"
        environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
        - KAFKA_LISTENERS=PLAINTEXT_HOST://0.0.0.0:9093,PLAINTEXT://0.0.0.0:9092
        - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_HOST
        networks:
            - lang-exchange-network
        restart: always
    kafdrop:
        image: obsidiandynamics/kafdrop
        restart: always
        ports:
          - "9000:9000"
        environment:
          KAFKA_BROKERCONNECT: kafka:9092
          # KAFKA_BROKERCONNECT: "101.99.31.28:9093"
          # KAFKA_BROKERCONNECT: "172.20.10.232:9092"
          JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
        networks:
            - lang-exchange-network
    ###############
    # le-api-gateway:
    #   image: thuongnguyen158/le-api-gateway:latest
    #   container_name: api-gateway
    #   environment:
    #     ASPNETCORE_ENVIRONMENT: Development

    #   depends_on:
    #     - le-file-service
    #     - consul
    #   networks:
    #     - lang-exchange-network
    #   restart: always
    #   ports:
    #   - "7777:80"
    ###############
    # access url to see http://localhost:5000/swagger/index.html
    le-file-service:
      image: thuongnguyen158/le-file-service:latest
      container_name: file-service
      environment:
        ASPNETCORE_ENVIRONMENT: Development
        S3_BUCKET_NAME: language-exchanged
        AWS_ACCESS_KEY_ID: AKIA5RKKGIJL6UQB7W4J
        AWS_SECRET_ACCESS_KEY: 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
        MINIO_HOST: http://127.0.0.1:9000
        CONSUL_URL: http://consul:8500

      depends_on:
        - consul
      networks:
        - lang-exchange-network
      restart: always
      ports:
      - "5000:80"
    ###############
    # access url to see http://localhost:5002/swagger/index.html
    le-user-service:
      image: thuongnguyen158/le-user-service:latest
      container_name: user-service
      environment:
        ASPNETCORE_ENVIRONMENT: Development
        CONSUL_URL: http://consul:8500
        DB_CONNECTION_STRING: Host=database-1.cvisbvujuezh.ap-southeast-1.rds.amazonaws.com;Port=5432;Database=langgeneral;Username=postgres;Password=t0ps3cr3tt0ps3cr3t
        SECRET_KEY: c9a56074-ac16-11ed-afa1-0242ac1200023b8f9f24-ac17-11ed-afa1-0242ac12000241c27614-ac17-11ed-afa1-0242ac120002
        NEO4J_DATABASE: neo4j
        #azure neo4j
        # NEO4J_HOST: bolt://20.195.209.186:7687
        # #aws neo4j
        NEO4J_HOST: bolt://54.151.158.181:7687
        #localhost neo4j
        # NEO4J_HOST: bolt://localhost:7687
        NEO4J_USER: neo4j
        NEO4J_PASSWORD: t0ps3cr3tt0ps3cr3t
        CHAT_DOMAIN: localhost
        MESSAGE_BUS_HOST: kafka:9092
        HOST_PREFIX: ""
        
      depends_on:
        - consul
      networks:
        - lang-exchange-network
      restart: always
      ports:
      - "5002:80"

    ##############
    le-notification-service:
      image: thuongnguyen158/le-notification-service:latest
      container_name: notification-service
      environment:
        ASPNETCORE_ENVIRONMENT: Development
        SECRET_KEY: c9a56074-ac16-11ed-afa1-0242ac1200023b8f9f24-ac17-11ed-afa1-0242ac12000241c27614-ac17-11ed-afa1-0242ac120002
        DB_CONNECTION_STRING: Host=database-1.cvisbvujuezh.ap-southeast-1.rds.amazonaws.com;Port=5432;Database=langgeneral;Username=postgres;Password=t0ps3cr3tt0ps3cr3t
        CRON_JOB_DB_CONNECTION_STRING: "Host=database-1.cvisbvujuezh.ap-southeast-1.rds.amazonaws.com;Port=5432;Database=background_cronjob;Username=postgres;Password=t0ps3cr3tt0ps3cr3t;Pooling=true;Minimum Pool Size=0;Maximum Pool Size=50"
        CONSUL_URL: http://consul:8500
        MESSAGE_BUS_HOST: kafka:9092
        HOST_PREFIX: ""
        
      depends_on:
        - consul
      networks:
        - lang-exchange-network
      restart: always
      ports:
      - "5003:80"
    ##############
    # access url to see http://localhost:8080
    # le-webapp-service:
    #   image: thuongnguyen158/le-web-app:latest
    #   container_name: web-app
    #   environment:
    #     REACT_APP_API_URL_ROOT: ""
    #   networks:
    #     - lang-exchange-network
    #   restart: always
    #   ports:
    #   - "8080:80"

    # neo4j:
    #   image: bitnami/neo4j:latest
    #   container_name: neo4j-local
    #   networks:
    #     - lang-exchange-network
    #   ports:
    #     - '7474:7474'
    #     - '7473:7473'
    #     - '7687:7687'
    #   volumes:
    #   - data:/bitnami
    #   restart: always
    #   environment:
    #       - NEO4J_PASSWORD=t0ps3cr3tt0ps3cr3t
    #       - NEO4J_BOLT_PORT_NUMBER=7687
    #       - NEO4J_HTTP_PORT_NUMBER=7474
    #       - NEO4J_HTTPS_PORT_NUMBER=7473
        
networks:
    lang-exchange-network:
        driver: bridge
volumes:
  data: