version: '3.4'

services:
    ###############
    consul:
        image: consul:${TAG:-latest}
        command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
        hostname: consul
        container_name: le-consul
        networks:
            - lang-exchange-network
        restart: always
        ports:
        - "8500:8500"
    ###############
    le-api-gateway:
      image: thuongnguyen158/le-api-gateway:latest
      container_name: api-gateway
      environment:
        ASPNETCORE_ENVIRONMENT: Development

      depends_on:
        - le-file-service
        - consul
      networks:
        - lang-exchange-network
      restart: always
      ports:
      - "7777:80"
    ###############
    le-file-service:
      image: thuongnguyen158/le-file-service:latest
      container_name: file-service
      environment:
        ASPNETCORE_ENVIRONMENT: Development
        S3_BUCKET_NAME: language-exchanged
        AWS_ACCESS_KEY_ID: empty
        AWS_SECRET_ACCESS_KEY: empty
        MINIO_HOST: http://127.0.0.1:9000
        CONSUL_URL: http://consul:8500

      depends_on:
        - consul
      networks:
        - lang-exchange-network
      restart: always
      # ports:
      # - "5000:80"
    

        
networks:
    lang-exchange-network:
        driver: bridge