version: '3.8'

services:
  le-user-service:
    image: thuongnguyen158/le-user-service:latest
    container_name: lec-user-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONSUL_URL: http://consul:8500
      DB_CONNECTION_STRING: Host=database-1.cvisbvujuezh.ap-southeast-1.rds.amazonaws.com;Port=5432;Database=langgeneral;Username=postgres;Password=t0ps3cr3tt0ps3cr3t
      SECRET_KEY: c9a56074-ac16-11ed-afa1-0242ac1200023b8f9f24-ac17-11ed-afa1-0242ac12000241c27614-ac17-11ed-afa1-0242ac120002
      NEO4J_DATABASE: neo4j
      NEO4J_HOST: bolt://18.140.71.40:7687
      # NEO4J_HOST: bolt://host.docker.internal:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: t0ps3cr3tt0ps3cr3t
      CHAT_DOMAIN: localhost
      MESSAGE_BUS_HOST: kafka:9092
      HOST_PREFIX: ""
    
    # depends_on:
    #   - consul
    #   - kafka
    #   - neo4j
    networks:
      - lang-exchange-network
    restart: always
    ports:
      - "5002:80"
      
networks:
  lang-exchange-network:
    external: true
