version: '3.4'

services:
    le-api-gateway:
      image: thuongnguyen158/le-api-gateway:latest
      container_name: api-gateway
      environment:
        ASPNETCORE_ENVIRONMENT: Development
      networks:
        - lang-exchange-network
      restart: always
      ports:
      - "7777:80"
networks:
  lang-exchange-network:
    external: true

    