version: '3.4'

services:
    le-webapp-service:
      image: thuongnguyen158/le-web-app:latest
      container_name: web-app
      environment:
        REACT_APP_API_URL_ROOT: http://localhost:8080
      networks:
        - lang-exchange-network
      restart: always
      
networks:
  lang-exchange-network:
    external: true
